### ISSUE TITLE
有關於OAS3.0的設定問題

### ISSUE THREAD

**Issue by MosNotBuger** [yaochangyu/sample.dotblog#3]
在您建置的這個專案範例中「[WebApi2.IisOWIN.NET45](https://github.com/yaochangyu/sample.dotblog/tree/master/WebAPI/NSwag/Lab.NSwagDoc/WebApi2.IisOWIN.NET45)」，
如果我想要符合Open API 3.0的格式，
請問您知道在Startup裡要如何設定嗎?

目前網路上查到的都只有 .Net Core的方法，
但好像不適用WebApi2

**Comment by yaochangyu** [comment]
> 在您建置的這個專案範例中「[WebApi2.IisOWIN.NET45](https://github.com/yaochangyu/sample.dotblog/tree/master/WebAPI/NSwag/Lab.NSwagDoc/WebApi2.IisOWIN.NET45)」，
> 如果我想要符合Open API 3.0的格式，
> 請問您知道在Startup裡要如何設定嗎?
> 
> 目前網路上查到的都只有 .Net Core的方法，
> 但好像不適用WebApi2

Hi
參數設定應該都是差不多的，看看以下連結對你有沒有幫助
https://blog.miniasp.com/post/2019/12/21/ASP%E2%80%A4NET-Core-3-NSwag-OpenAPI-v3
